=== djordjenrt5117/Provera-Znanja/adresar.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.w3schools.com" 
elementFormDefault="qualified" 
targetNamespace="http://www.w3schools.com" 
xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Osobe">
    <xs:complexType>
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element ref="Osoba"/>
        </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Osoba">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="PunoIme"/>
            <xs:element ref="DatumRodjenja"/>
            <xs:element ref="Adresa"/>
            <xs:element minOccurs="1" maxOccurs="unbounded" ref="Email"/>
        </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="PunoIme">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="Ime"/>
            <xs:element minOccurs="0" maxOccurs="1" ref="SrednjeIme"/>
            <xs:element ref="Prezime"/>
        </xs:sequence>
    </xs:complexType>
  </xs:element>

<xs:element name="Ime">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
            <xs:maxLength value="30"/>
        </xs:restriction>
    </xs:simpleType>   
</xs:element>

<xs:element name="SrednjeIme" type="xs:string"/>

<xs:element name="Prezime" type="xs:string"/>

  <xs:element name="DatumRodjenja">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="Dan"/>
            <xs:element ref="Mesec"/>
            <xs:element ref="Godina"/>
        </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Dan">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9]|[1-2][0-9]|3[0-1]"/>
        </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="Mesec">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9]|1[0-2]"/>
        </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="Godina" type="xs:string"/>

  <xs:element name="Adresa">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute default="privremena" name="tip">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="privremena"/>
                            <xs:enumeration value="stalna"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="Email">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="emailRestrikcija">
                <xs:attribute name="tip">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="privatni"/>
                            <xs:enumeration value="sluzbeni"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="emailRestrikcija">
    <xs:restriction base="xs:string">
        <xs:pattern value="\c{1,20}@\c{4,8}.com"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== djordjenrt5117/Provera-Znanja/adresar.xml
<?xml version="1.0" encoding="utf-8"?>
<Osobe xmlns="http://www.w3schools.com"
         xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
         xs:schemaLocation="http://www.w3schools.com adresar.xsd">
    <Osoba>
        <PunoIme>
            <Ime>asd</Ime>
            <SrednjeIme>asd</SrednjeIme>
            <Prezime>asd</Prezime>
        </PunoIme>

        <DatumRodjenja>
            <Dan>11</Dan>
            <Mesec>22</Mesec>
            <Godina>2003</Godina>
        </DatumRodjenja>

        <Adresa tip="privremena">asdasd</Adresa>

        <Email tip="privatni">dasdasd</Email>
    </Osoba>
</Osobe>
